// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for news documents */
interface NewsDocumentData {
  /**
   * Slice Zone field in *news*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<NewsDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *news*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Image field in *news*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *news*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *news → Slice Zone*
 *
 */
type NewsDocumentDataSlicesSlice = HeadNewsSlice | NewsTextSlice;
/**
 * news document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;
export type AllDocumentTypes = NewsDocument;
/**
 * Primary content in HeadNews → Primary
 *
 */
interface HeadNewsSliceDefaultPrimary {
  /**
   * Title field in *HeadNews → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: head_news.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
  /**
   * Subtitle field in *HeadNews → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: head_news.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismic.KeyTextField;
  /**
   * Main Image field in *HeadNews → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: head_news.primary.main_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  main_image: prismic.ImageField<never>;
}
/**
 * Default variation for HeadNews Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeadNewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadNewsSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *HeadNews*
 *
 */
type HeadNewsSliceVariation = HeadNewsSliceDefault;
/**
 * HeadNews Shared Slice
 *
 * - **API ID**: `head_news`
 * - **Description**: `HeadNews`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeadNewsSlice = prismic.SharedSlice<
  "head_news",
  HeadNewsSliceVariation
>;
/**
 * Primary content in NewsText → Primary
 *
 */
interface NewsTextSliceDefaultPrimary {
  /**
   * Content field in *NewsText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_text.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
}
/**
 * Default variation for NewsText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NewsTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsTextSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *NewsText*
 *
 */
type NewsTextSliceVariation = NewsTextSliceDefault;
/**
 * NewsText Shared Slice
 *
 * - **API ID**: `news_text`
 * - **Description**: `NewsText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NewsTextSlice = prismic.SharedSlice<
  "news_text",
  NewsTextSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      NewsDocumentData,
      NewsDocumentDataSlicesSlice,
      NewsDocument,
      AllDocumentTypes,
      HeadNewsSliceDefaultPrimary,
      HeadNewsSliceDefault,
      HeadNewsSliceVariation,
      HeadNewsSlice,
      NewsTextSliceDefaultPrimary,
      NewsTextSliceDefault,
      NewsTextSliceVariation,
      NewsTextSlice,
    };
  }
}
