// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  head_news: dynamic(() => import("./HeadNews")),
  news_text: dynamic(() => import("./NewsText")),
};
